baseURL = "https://oclus.github.com/"
languageCode = "en-us"
title = "Oclus"

publishdir = "docs"
FootnoteReturnLinkContents = "↑"
[author]
    name = "gocs"
    description = "hellow"

# partials/header-menu.html
[menu]

    [[menu.main]]
        identifier = "about"
        name = "about"
        title = "about section"
        url = "/about"
        weight = -110

    [[menu.main]]
        identifier = "posts"
        name = "posts"
        title = "posts section"
        url = "/posts/"
        weight = -110

[params]
    description = "hello, google.com!"
    # partials/head.html
    css = [
        "/css/color.css",
        "/css/summary.css",
        "/css/single.css",
        "/css/fonts.css",
        "/css/whitespace.css",
        "/css/water.css",
    ]
    github = "https://github.com/oclus"
    reddit = ""
    discord = ""
    linkedin = ""
    instagram = ""
    facebook = ""
    twitter = ""